apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack
  labels:
    app: snack
spec:
  selector:
    matchLabels:
      app: snack
  template:
    metadata:
      labels:
        app: snack
        tier: web
    spec:
      containers:
      - name: snack
        image: snack-image
        ports:
        - containerPort: 8083
        resources:
          requests:
            cpu: "10m"
