apiVersion: apps/v1
kind: Deployment
metadata:
  name: vigoda
  labels:
    app: vigoda
spec:
  selector:
    matchLabels:
      app: vigoda
  template:
    metadata:
      labels:
        app: vigoda
        tier: web
    spec:
      containers:
      - name: vigoda
        image: vigoda-image
        env:
        - name: TEMPLATE_DIR
          value: "/go/src/github.com/windmilleng/servantes/vigoda/web/templates"
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "10m"
